INSERT INTO COUNTRY (ID, NAME) VALUES (1, 'US')
INSERT INTO COUNTRY (ID, NAME) VALUES (2, 'UK')
 

INSERT INTO AUTHOR (ID, NAME,COUNTRY_ID) VALUES (1, 'Engineering',1)
INSERT INTO AUTHOR (ID, NAME,COUNTRY_ID) VALUES (2, 'CA13',2)
INSERT INTO AUTHOR (ID, NAME,COUNTRY_ID) VALUES (3, 'CA19',1)

INSERT INTO POST (ID, NAME, AUTHOR_ID ) VALUES (1, 'Joan',   1 )
INSERT INTO POST (ID, NAME, AUTHOR_ID ) VALUES (2, 'Sarah',  2 )
INSERT INTO POST (ID, NAME, AUTHOR_ID ) VALUES (3, 'John',  2 )
INSERT INTO POST (ID, NAME, AUTHOR_ID ) VALUES (4, 'Roberts',   2 )
INSERT INTO POST (ID, NAME, AUTHOR_ID ) VALUES (5, 'Peter',   2 )
INSERT INTO POST (ID, NAME, AUTHOR_ID ) VALUES (6, 'Frank',  3 )
INSERT INTO POST (ID, NAME, AUTHOR_ID ) VALUES (7, 'Scott', 1 )
INSERT INTO POST (ID, NAME, AUTHOR_ID ) VALUES (8, 'Sue',  1 )
INSERT INTO POST (ID, NAME, AUTHOR_ID ) VALUES (9, 'Stephanie',   1 )
INSERT INTO POST (ID, NAME, AUTHOR_ID ) VALUES (10, 'Jennifer',   1 )
INSERT INTO POST (ID, NAME, AUTHOR_ID ) VALUES (11, 'Marcus',   3 )
 